artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1pSc7r2YZ5H9oUA2-Qo8aL8EY-xMz3o9g/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/yolov8n.pt 
  updated_base_model_path: artifacts/prepare_base_model/best.pt 
  model_name: yolov8n


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/best.pt
  training_data: artifacts/data_ingestion/data.yaml

evaluation:
  root_dir: artifacts/evaluation
  path_of_model: artifacts/training/best.pt
  training_data: artifacts/data_ingestion/data.yaml
