artifacts_root: artifacts
data_ingestion:
  local_data_file: artifacts/data_ingestion/data.zip
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/12FeWb_KqhTW1t_6Fxi5inmHwOCmhrZC9/view?usp=sharing
  unzip_dir: artifacts/data_ingestion
evaluation:
  path_of_model: artifacts/model_training_runs/best.pt
  root_dir: artifacts/evaluation
  training_data: artifacts/data_ingestion/data.yaml
prepare_base_model:
  base_model_path: artifacts/prepare_base_model\yolo12n.pt
  model_name: yolo12n.pt
  root_dir: artifacts/prepare_base_model
  updated_base_model_path: artifacts/prepare_base_model/best.pt
training:
  root_dir: artifacts/model_training_runs
  trained_model_path: artifacts/model_training_runs/best.pt
  training_data: artifacts/data_ingestion/data.yaml
